# Generated by Django 4.0.2 on 2023-01-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docAnalisisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=75)),
                ('nombre', models.CharField(default='', max_length=75)),
                ('objetivo', models.CharField(default='', max_length=500)),
                ('identificador', models.CharField(default='', max_length=30)),
                ('ind_met', models.CharField(default='', max_length=500)),
                ('des_actividades', models.CharField(default='', max_length=750)),
                ('diagrama_flujo', models.ImageField(upload_to='diagramas_flujo')),
                ('categoria', models.CharField(default='', max_length=75)),
                ('salida', models.CharField(default='', max_length=500)),
                ('frecuencia', models.CharField(default='', max_length=100)),
                ('introE', models.CharField(default='', max_length=500)),
                ('alcanceE', models.CharField(default='', max_length=500)),
                ('objetivosE', models.CharField(default='', max_length=500)),
                ('arq1', models.ImageField(blank=True, null=True, upload_to='arquitectura')),
                ('arq2', models.ImageField(blank=True, null=True, upload_to='arquitectura')),
                ('arq3', models.ImageField(blank=True, null=True, upload_to='arquitectura')),
                ('comp1', models.ImageField(blank=True, null=True, upload_to='componentes')),
                ('comp2', models.ImageField(blank=True, null=True, upload_to='componentes')),
                ('comp3', models.ImageField(blank=True, null=True, upload_to='componentes')),
                ('des_componentesE', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='docPruebasUnitariasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=75)),
                ('nombre_proceso', models.CharField(default='', max_length=75)),
                ('objetivo', models.CharField(default='', max_length=500)),
                ('identificador', models.CharField(default='', max_length=30)),
                ('ind_met', models.CharField(default='', max_length=500)),
                ('des_actividades', models.CharField(default='', max_length=750)),
                ('diagrama_flujo', models.ImageField(upload_to='diagramas_flujo')),
                ('categoria', models.CharField(default='', max_length=75)),
                ('salida', models.CharField(default='', max_length=500)),
                ('frecuencia', models.CharField(default='', max_length=100)),
                ('nombre_proyecto', models.CharField(default='', max_length=75)),
                ('encargado', models.CharField(default='', max_length=75)),
                ('fase', models.CharField(default='', max_length=100)),
                ('lugar_fecha', models.CharField(default='', max_length=200)),
                ('req', models.CharField(default='', max_length=500)),
                ('repo', models.CharField(default='', max_length=250)),
                ('selec', models.CharField(default='', max_length=250)),
                ('cod1', models.ImageField(blank=True, null=True, upload_to='codigo')),
                ('cod2', models.ImageField(blank=True, null=True, upload_to='codigo')),
                ('cod3', models.ImageField(blank=True, null=True, upload_to='codigo')),
                ('lineas', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='docRequisitosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=75)),
                ('nombre_proceso', models.CharField(default='', max_length=75)),
                ('objetivo', models.CharField(default='', max_length=500)),
                ('identificador', models.CharField(default='', max_length=30)),
                ('ind_met', models.CharField(default='', max_length=500)),
                ('des_actividades', models.CharField(default='', max_length=750)),
                ('categoria', models.CharField(default='', max_length=75)),
                ('salida', models.CharField(default='', max_length=500)),
                ('frecuencia', models.CharField(default='', max_length=100)),
                ('proposito', models.CharField(default='', max_length=500)),
                ('alcance', models.CharField(default='', max_length=500)),
                ('referencias', models.ImageField(blank=True, null=True, upload_to='referencias')),
                ('funcionalidades', models.CharField(default='', max_length=500)),
                ('clases', models.CharField(default='', max_length=500)),
                ('entorno', models.CharField(default='', max_length=100)),
                ('req_f', models.CharField(default='', max_length=600)),
                ('req_nf', models.CharField(default='', max_length=600)),
            ],
        ),
    ]
