# Generated by Django 4.0.2 on 2023-01-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='docRgistroRastreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=75)),
                ('objetivo', models.CharField(default='', max_length=500)),
                ('identificador', models.CharField(default='', max_length=30)),
                ('ind_met', models.CharField(default='', max_length=500)),
                ('des_actividades', models.CharField(default='', max_length=750)),
                ('diagrama_flujo', models.ImageField(blank=True, null=True, upload_to='diagramas_flujo')),
                ('categoria', models.CharField(default='', max_length=75)),
                ('salida', models.CharField(default='', max_length=500)),
                ('frecuencia', models.CharField(default='', max_length=100)),
                ('nombre_proyecto', models.CharField(default='', max_length=75)),
                ('version', models.CharField(default='', max_length=75)),
                ('puesto', models.CharField(default='', max_length=75)),
                ('fecha', models.CharField(default='', max_length=75)),
                ('herramienta', models.CharField(default='', max_length=75)),
                ('link', models.CharField(default='', max_length=75)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.AlterField(
            model_name='docanalisismodel',
            name='diagrama_flujo',
            field=models.ImageField(blank=True, null=True, upload_to='diagramas_flujo'),
        ),
    ]
