# Generated by Django 4.0.2 on 2023-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_docrgistrorastreo_nombre_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='docPruebasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=75)),
                ('nombre_proceso', models.CharField(default='', max_length=75)),
                ('objetivo', models.CharField(default='', max_length=500)),
                ('identificador', models.CharField(default='', max_length=30)),
                ('ind_met', models.CharField(default='', max_length=500)),
                ('des_actividades', models.CharField(default='', max_length=750)),
                ('diagrama_flujo', models.ImageField(blank=True, null=True, upload_to='diagramas_flujo')),
                ('categoria', models.CharField(default='', max_length=75)),
                ('salida', models.CharField(default='', max_length=500)),
                ('frecuencia', models.CharField(default='', max_length=100)),
                ('tipo_errores', models.CharField(default='', max_length=500)),
                ('criterios_aceptacion', models.ImageField(blank=True, null=True, upload_to='criterios_aceptacion')),
            ],
        ),
        migrations.RenameModel(
            old_name='docRgistroRastreo',
            new_name='docRgistroRastreoModel',
        ),
    ]
