# Generated by Django 4.0.2 on 2023-01-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_docpruebasmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpruebasmodel',
            name='caso_prueba',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='caso_prueba_img',
            field=models.ImageField(blank=True, null=True, upload_to='caso_prueba'),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='consclusiones',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='criterios_usa_img',
            field=models.ImageField(blank=True, null=True, upload_to='criterios_usabilidad'),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='criterios_usabilidad',
            field=models.ImageField(blank=True, null=True, upload_to='criterios_usabilidad'),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='folio_caso',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='metricas',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='reporte_folio',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='reporte_prueba',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='docpruebasmodel',
            name='reporte_prueba_img',
            field=models.ImageField(blank=True, null=True, upload_to='reporte_prueba'),
        ),
    ]
