# Generated by Django 4.0.2 on 2023-01-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_docpruebasmodel_caso_prueba_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docpruebasmodel',
            old_name='consclusiones',
            new_name='conclusiones',
        ),
        migrations.AlterField(
            model_name='docpruebasmodel',
            name='criterios_usa_img',
            field=models.ImageField(blank=True, null=True, upload_to='criterios_usa_img'),
        ),
        migrations.AlterField(
            model_name='docpruebasmodel',
            name='criterios_usabilidad',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='docpruebasmodel',
            name='diagrama_flujo',
            field=models.ImageField(blank=True, null=True, upload_to='diagrama_flujo'),
        ),
    ]
