# Generated by Django 4.0.2 on 2023-02-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_rename_consclusiones_docpruebasmodel_conclusiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequisitosmodel',
            name='diagrama_flujo',
            field=models.ImageField(blank=True, upload_to='diagrama_flujo'),
        ),
    ]
